config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :news
  devise_for :users

  root 'home#index' 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :news

end

app/models/news.rb
class News < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum :role, [:anonimo, :usuario, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_s
    self.email
  end

end
# rails g scaffold News title:string imagen:string description:text 
# rails g scaffold Comment content:text user:references news:references

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    redirect_to root_path
  end

  # GET /comments/1 or /comments/1.json
  def show
    redirect_to root_path
  end

  # GET /comments/new
  def new
    if user_signed_in?
      @noticia = params[:noticia]
      @comment = Comment.new
    else
      redirect_to root_path, alert: "Debes iniciar sesión para dejar un comentario."
    end
  end

  # GET /comments/1/edit
  def edit
    if user_signed_in?
      comment_id = params[:id]
      @comment = Comment.find(comment_id)
      if current_user.id == @comment.user_id

      else 
        redirect_to comment_path(comment_id), alert: "No puedes modificar un comentario del que no seas el autor."
      end
    else
      redirect_to comment_path(comment_id), alert: "Debes iniciar sesión para modificar tu comentario."
    end
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to news_url(@comment.news_id), notice: "Comentario creado correctamente." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    if user_signed_in?
      comment_id = params[:id]
      @comment = Comment.find(comment_id)
      if current_user.id == @news.user_id
        respond_to do |format|
          if @comment.update(comment_params)
            format.html { redirect_to news_url(@comment.news_id), notice: "Comentario actualizado correctamente." }
            format.json { render :show, status: :ok, location: @comment }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
        end
      else 
        redirect_to comment_path(comment_id), alert: "No puedes actualizar un comentario del que no seas el autor."
      end
    else
      redirect_to comment_path(comment_id), alert: "Debes iniciar sesión para actualizar tu comentario."
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    if user_signed_in?
      comment_id = params[:id]
      @comment = Comment.find(comment_id)
      if current_user.id == @comment.user_id || current_user.role == User.roles.key(2).to_s
        @comment.destroy
        respond_to do |format|
          format.html { redirect_to news_url(@comment.news_id), notice: "El comentario ha sido eliminado correctamente" }
          format.json { head :no_content }
        end
      else 
        redirect_to comment_path(comment_id), alert: "No puedes eliminar un comentario del que no seas el autor."
      end
    else
      redirect_to comment_path(comment_id), alert: "Debes iniciar sesión para eliminar tu comentario."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :news_id).merge(user_id: current_user.id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @news = News.all
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    redirect_to root_path
  end

  # GET /news/1 or /news/1.json
  def show
    @news = News.find(params[:id])
    @comments = @news.comments
  end

  # GET /news/new
  def new
    if user_signed_in?
      @news = News.new
    else
      redirect_to root_path, alert: "Debes iniciar sesión para crear una noticia."
    end
  end

  # GET /news/1/edit
  def edit
    if user_signed_in?
      news_id = params[:id]
      @news = News.find(news_id)
      if current_user.id == @news.user_id

      else 
        redirect_to news_path(news_id), alert: "No puedes modificar una noticia de la que no seas el autor."
      end
    else
      redirect_to news_path(news_id), alert: "Debes iniciar sesión para modificar tu noticia."
    end
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)
    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    if user_signed_in?
      news_id = params[:id]
      @news = News.find(news_id)
      if current_user.id == @news.user_id
        respond_to do |format|
          if @news.update(news_params)
            format.html { redirect_to news_url(@news), notice: "News was successfully updated." }
            format.json { render :show, status: :ok, location: @news }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @news.errors, status: :unprocessable_entity }
          end
        end
      else 
        redirect_to news_path(news_id), alert: "No puedes actualizar una noticia de la que no seas el autor."
      end
    else
      redirect_to news_path(news_id), alert: "Debes iniciar sesión para actualizar tu noticia."
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    if user_signed_in?
      news_id = params[:id]
      if current_user.id == @news.user_id || current_user.role == User.roles.key(2).to_s
        @news.destroy
        respond_to do |format|
          format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
          format.json { head :no_content }
        end
      else 
        redirect_to news_path(news_id), alert: "No puedes eliminar una noticia de la que no seas el autor."
      end
    else
      redirect_to news_path(news_id), alert: "Debes iniciar sesión para eliminar tu noticia."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :imagen, :description).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>News:</strong>
    <%= comment.news_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :content, "Comentario", style: "display: block", class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.hidden_field :news_id, value: @noticia %>
  </div>

  <div class="mb-3">
    <%= form.submit "Agrega el comentario", class: "btn btn-success w-100" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<div class="row py-5">
  <div class="col-12">
    <h1 class="text-center">Nuevo comentario</h1>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= render "form", comment: @comment %>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= link_to "Back to comments", comments_path%>
  </div>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="row py-5">
    <div class="col-12">
        <h1 class="text-center">The Rial News</h1>
        <p class="text-center">Las noticias más del corte.</p>
    </div>
</div>
<div class="row"> <!-- añadyr gy-3 para bordes del eje y -->
    <div class="col-12">
        <% @news.each do |new| %>
            <div class="card">
            <img src='<%= new.imagen %>' class="card-img-top" style="width: 100%; height:350px;">
            <div class="card-body">
                <%= render new %>
                <div class="row">
                    <div class="col-6">
                        <%= link_to 'Comenta', "/comments/new?noticia=#{new.id}", class: 'btn btn-primary w-100' %>
                    </div>
                    <div class="col-6">
                        <%= link_to 'Más información', news_path(new.id), class: 'btn btn-secondary w-100' %>
                    </div>
                </div>
            </div>
          </div>
        <% end %>
    </div>
</div>
<div class="row py-5">
    <div class="col-12">
        <%= link_to "Nueva noticia", new_news_path, class: "btn btn-success w-100" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Las Noticias Verdaderas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div id="flash-messages">
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>">
            <%= message %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <script src="https://kit.fontawesome.com/178860d74b.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, "Título", style: "display: block", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :imagen, "Imagen", style: "display: block", class: "form-label" %>
    <%= form.text_field :imagen, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción", style: "display: block", class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Modifica", class: "btn btn-success w-100"  %>
  </div>
<% end %>

app/views/news/_news.html.erb
<h2 class="card-title text-center"><%= news.title %></h2>
<p class="card-text"><%= news.description %></p>
<footer class="blockquote-footer">Autor: <cite title="Source Title"><%= news.user.email %></cite></footer>

app/views/news/edit.html.erb
<div class="row py-5">
  <div class="col-12">
    <h1 class="text-center">Editing news</h1>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= render "form", news: @news %>
  </div>
</div>

<div class="row py-5">
  <div class="col-6">
    <%= link_to "Vuelve a esta noticia", @news, class: "btn btn-primary w-100" %>
  </div>
  <div class="col-6">
    <%= link_to "Vuelve a las noticias", root_path, class: "btn btn-secondary w-100" %>
  </div>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>News</h1>

<div id="news">
  <% @news.each do |news| %>
    <%= render news %>
    <p>
      <%= link_to "Show this news", news %>
    </p>
  <% end %>
</div>

<%= link_to "New news", new_news_path %>

app/views/news/new.html.erb
<div class="row py-5">
  <div class="col-12">
   <h1 class="text-center">Nueva noticia</h1> 
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= render "form", news: @news %>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= link_to "Back to news", root_path %>
  </div>
</div>

app/views/news/show.html.erb
<div class="row py-5">
  <div class="col-12">
    <h2 class="text-center">Noticia #<%= @news.id %></h2>
  </div>
</div>

<div class="row py-5">
  <p style="color: green"><%= notice %></p>
  <div class="card">
    <img src='<%= @news.imagen %>' class="card-img-top" style="width: 100%; height:350px;">
    <div class="card-body">
      <%= render @news %>
    </div>
  </div>  
</div>

<div class="row py-5">
  <h4 class="text-center">Comentarios:</h4>
  <% @comments.each do |comment| %>
    <div>
      <p><%= comment.content %></p>
      <footer class="blockquote-footer">Autor: <cite title="Source Title"><%= comment.user.email %></cite></footer>
    </div>
    <hr>
    <% if current_user.role == User.roles.key(2).to_s %>
      <div class="col-12">
        <%= button_to "Elimina el comentario", comment_path(comment), method: :delete, class: "btn btn-danger w-100" %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= link_to 'Comenta', "/comments/new?noticia=#{@news.id}", class: 'btn btn-success w-100' %>
  </div>
</div>

<div class="row py-5">
  <div class="col-4">
    <%= link_to "Vuelve a las noticias", root_path, class: "btn btn-primary w-100" %>
  </div>
  <div class="col-4">
    <%= link_to "Edita la noticia", edit_news_path(@news), class: "btn btn-warning w-100" %>
  </div>
  <div class="col-4">
    <%= button_to "Elimina la noticia", @news, method: :delete, class: "btn btn-danger w-100" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer style="background-color: black; color: white;">
    <div class="container">
        <div class="row py-5">
            <h4 class="text-center py-3">The Rial News</h4>
            <div class="col-6">
                <p>Contacto</p>
                <ul>
                    <li>+56912345678</li>
                    <li>contacto@therialnews.cl</li>
                </ul>
            </div>
            <div class="col-6">
                <p>Dirección:</p>
                <ul>
                    <li>Av. Poncho #123</li>
                    <li>Renca, Región Metropolitana</li>
                </ul>
            </div>
            <h4 class="text-center py-5">Todos los derechos reservados.</h4>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/"><%= image_tag("navbar/logo", alt: "Logo", style: "width: 50px; height: 50px;" ) %> TheRialNews</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/"><i class="fa-solid fa-house"></i> Home</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
            <i class="fa-solid fa-user"></i> Bienvenido/a <%= current_user.email %>
            <% else %>
            <i class="fa-solid fa-user-secret"></i> Usuario anónimo
            <% end %>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <% if user_signed_in? %>
              <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
            <% else %>
              <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
              <li><hr class="dropdown-divider" style="border-top: 1px solid #fff;"></li>
              <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>